export const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS';
export const GET_ALL_TYPES = 'GET_ALL_TYPES';
export const GET_POKEMON_DETAIL = 'GET_POKEMON_DETAIL';
export const CLEAN_POKEMON_DETAIL = 'CLEAN_POKEMON_DETAIL';
export const SEARCH_POKEMON = 'SEARCH_POKEMON';
export const SORT_POKEMON = 'SORT_POKEMON';
export const FILTER_POKEMON = 'FILTER_POKEMON'; 